[project]
name = "aws-boto3-modules"
version = "0.1.0"
description = "A modular Route 53 automation tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies =  [
    "boto3>=1.38.43",
    "botocore>=1.38.43",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.4.1",
    "moto>=5.1.6",
]